// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqv7cRi7Jy_j0qUt93cFYEaBYLKd64roc',
    appId: '1:967791373548:web:f78e93d74fb026c840c9c9',
    messagingSenderId: '967791373548',
    projectId: 'serw-41cfb',
    authDomain: 'serw-41cfb.firebaseapp.com',
    storageBucket: 'serw-41cfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvelDI6rRUSzKMOdqbIS51wOUOoSVyvSQ',
    appId: '1:967791373548:android:17f0916d1a1029ff40c9c9',
    messagingSenderId: '967791373548',
    projectId: 'serw-41cfb',
    storageBucket: 'serw-41cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJG0L2KM46r1_1nuuyiWJ40q57FihWcIM',
    appId: '1:967791373548:ios:bfd3ba7b181a3de940c9c9',
    messagingSenderId: '967791373548',
    projectId: 'serw-41cfb',
    storageBucket: 'serw-41cfb.appspot.com',
    iosClientId: '967791373548-l1sf75n3ft9tk4q6ak4o0ahtd2c42v37.apps.googleusercontent.com',
    iosBundleId: 'com.example.serw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJG0L2KM46r1_1nuuyiWJ40q57FihWcIM',
    appId: '1:967791373548:ios:bfd3ba7b181a3de940c9c9',
    messagingSenderId: '967791373548',
    projectId: 'serw-41cfb',
    storageBucket: 'serw-41cfb.appspot.com',
    iosClientId: '967791373548-l1sf75n3ft9tk4q6ak4o0ahtd2c42v37.apps.googleusercontent.com',
    iosBundleId: 'com.example.serw',
  );
}
